openapi: 3.0.1
info:
  title: helloapi
  description: ''
  version: '1.0'
servers:
  - url: https://apimanagement-qa-service.azure-api.net/api
paths:
  /hello:
    get:
      summary: hello
      operationId: hello
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]